# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sd_pb2 as proto_dot_sd__pb2


class SdServiceStub(object):
    """定义服务接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.text2img = channel.unary_unary(
                '/SdService/text2img',
                request_serializer=proto_dot_sd__pb2.SdText2ImgRequest.SerializeToString,
                response_deserializer=proto_dot_sd__pb2.SdText2ImgResponse.FromString,
                )
        self.img2img = channel.unary_unary(
                '/SdService/img2img',
                request_serializer=proto_dot_sd__pb2.SdImg2ImgRequest.SerializeToString,
                response_deserializer=proto_dot_sd__pb2.SdImg2ImgResponse.FromString,
                )


class SdServiceServicer(object):
    """定义服务接口
    """

    def text2img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def img2img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'text2img': grpc.unary_unary_rpc_method_handler(
                    servicer.text2img,
                    request_deserializer=proto_dot_sd__pb2.SdText2ImgRequest.FromString,
                    response_serializer=proto_dot_sd__pb2.SdText2ImgResponse.SerializeToString,
            ),
            'img2img': grpc.unary_unary_rpc_method_handler(
                    servicer.img2img,
                    request_deserializer=proto_dot_sd__pb2.SdImg2ImgRequest.FromString,
                    response_serializer=proto_dot_sd__pb2.SdImg2ImgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SdService(object):
    """定义服务接口
    """

    @staticmethod
    def text2img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SdService/text2img',
            proto_dot_sd__pb2.SdText2ImgRequest.SerializeToString,
            proto_dot_sd__pb2.SdText2ImgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def img2img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SdService/img2img',
            proto_dot_sd__pb2.SdImg2ImgRequest.SerializeToString,
            proto_dot_sd__pb2.SdImg2ImgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
