# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproto/sd.proto\"\x8c\x01\n\x11SdText2ImgRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0c\n\x04seed\x18\x05 \x01(\x05\x12\r\n\x05steps\x18\x06 \x01(\x05\x12\x12\n\nbatch_size\x18\x07 \x01(\x05\"$\n\x12SdText2ImgResponse\x12\x0e\n\x06\x62\x61se64\x18\x01 \x03(\t\"\xb0\x01\n\x10SdImg2ImgRequest\x12\x15\n\rbase64_images\x18\x01 \x03(\t\x12\x0c\n\x04mask\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x04 \x01(\t\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x0c\n\x04seed\x18\x07 \x01(\x05\x12\r\n\x05steps\x18\x08 \x01(\x05\x12\x12\n\nbatch_size\x18\t \x01(\x05\"#\n\x11SdImg2ImgResponse\x12\x0e\n\x06\x62\x61se64\x18\x01 \x03(\t2v\n\tSdService\x12\x35\n\x08text2img\x12\x12.SdText2ImgRequest\x1a\x13.SdText2ImgResponse\"\x00\x12\x32\n\x07img2img\x12\x11.SdImg2ImgRequest\x1a\x12.SdImg2ImgResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _globals['_SDTEXT2IMGREQUEST']._serialized_start=19
  _globals['_SDTEXT2IMGREQUEST']._serialized_end=159
  _globals['_SDTEXT2IMGRESPONSE']._serialized_start=161
  _globals['_SDTEXT2IMGRESPONSE']._serialized_end=197
  _globals['_SDIMG2IMGREQUEST']._serialized_start=200
  _globals['_SDIMG2IMGREQUEST']._serialized_end=376
  _globals['_SDIMG2IMGRESPONSE']._serialized_start=378
  _globals['_SDIMG2IMGRESPONSE']._serialized_end=413
  _globals['_SDSERVICE']._serialized_start=415
  _globals['_SDSERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
